# Simple Linear Regression
# By Giriraj Vaishnav
There are five basic steps when you’re implementing linear regression:

1. Import the packages and classes you need.
2. Provide data to work with and eventually do appropriate transformations.
3. Create a regression model and fit it with existing data.
4. Check the results of model fitting to know whether the model is satisfactory.
5. Apply the model for predictions.


In [1]:
# Import packages and classes

import numpy as np
from sklearn.linear_model import LinearRegression

In [3]:
# Provide Data

x = np.array([5, 15, 25, 35, 45, 55]).reshape((-1, 1))
y = np.array([5, 20, 14, 32, 22, 38])

print(x)
print(y)

[[ 5]
 [15]
 [25]
 [35]
 [45]
 [55]]
[ 5 20 14 32 22 38]


In [4]:
# Create a model and fit it

model = LinearRegression()
model.fit(x,y)

LinearRegression()

In [6]:
# Get result

r_sq = model.score(x, y)
print('coefficient of determination:', r_sq)

print('intercept:', model.intercept_)

print('slope:', model.coef_)

# For 2 D Array
# new_model = LinearRegression().fit(x, y.reshape((-1, 1)))
# print('intercept:', new_model.intercept_)
# print('slope:', new_model.coef_)

coefficient of determination: 0.7158756137479542
intercept: 5.633333333333329
slope: [0.54]


In [8]:
# Predict responses

y_pred = model.predict(x)
print('predicted response:', y_pred, sep='\n')

# y_pred = model.intercept_ + model.coef_ * x
# print('predicted response:', y_pred, sep='\n')

predicted response:
[ 8.33333333 13.73333333 19.13333333 24.53333333 29.93333333 35.33333333]
